
package AdastraWS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdastraWebService", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/C:/source/AdastraReceiver/WSDL/IOWLogica.wsdl")
public class AdastraWebService
    extends Service
{

    private final static URL ADASTRAWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADASTRAWEBSERVICE_EXCEPTION;
    private final static QName ADASTRAWEBSERVICE_QNAME = new QName("http://tempuri.org/", "AdastraWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/source/AdastraReceiver/WSDL/IOWLogica.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADASTRAWEBSERVICE_WSDL_LOCATION = url;
        ADASTRAWEBSERVICE_EXCEPTION = e;
    }

    public AdastraWebService() {
        super(__getWsdlLocation(), ADASTRAWEBSERVICE_QNAME);
    }

    public AdastraWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADASTRAWEBSERVICE_QNAME, features);
    }

    public AdastraWebService(URL wsdlLocation) {
        super(wsdlLocation, ADASTRAWEBSERVICE_QNAME);
    }

    public AdastraWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADASTRAWEBSERVICE_QNAME, features);
    }

    public AdastraWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdastraWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdastraWebServiceSoap
     */
    @WebEndpoint(name = "AdastraWebServiceSoap")
    public AdastraWebServiceSoap getAdastraWebServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "AdastraWebServiceSoap"), AdastraWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdastraWebServiceSoap
     */
    @WebEndpoint(name = "AdastraWebServiceSoap")
    public AdastraWebServiceSoap getAdastraWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "AdastraWebServiceSoap"), AdastraWebServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns AdastraWebServiceSoap
     */
    @WebEndpoint(name = "AdastraWebServiceSoap1")
    public AdastraWebServiceSoap getAdastraWebServiceSoap1() {
        return super.getPort(new QName("http://tempuri.org/", "AdastraWebServiceSoap1"), AdastraWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdastraWebServiceSoap
     */
    @WebEndpoint(name = "AdastraWebServiceSoap1")
    public AdastraWebServiceSoap getAdastraWebServiceSoap1(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "AdastraWebServiceSoap1"), AdastraWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADASTRAWEBSERVICE_EXCEPTION!= null) {
            throw ADASTRAWEBSERVICE_EXCEPTION;
        }
        return ADASTRAWEBSERVICE_WSDL_LOCATION;
    }

}
