version: 0.0
os: linux
files:
  - source: /FrontEnd/dist
    destination: //opt/tomcat/webapps/discovery-dashboard
  - source: /API/target/API-0.0.1
    destination: //opt/tomcat/webapps/discovery-dashboard
hooks:
  BeforeInstall:
    - location: aws_scripts/cleanup
      timeout: 300
      runas: root
